Release 2.0.3
Changes since 2.0.2:
- Fixed a bug in the command line argument parser that resulted in error
  messages like
    Error: Error 4 while parsing argument 5
    Error: Invalid argument for option --system=: false